name: 🔂 Unit tests

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11-dev"]

    name: Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"

      - run: poetry env use ${{ matrix.python-version }}
      - run: poetry run python --version
      - run: poetry install
        if: steps.setup-python.outputs.cache-hit != 'true'

      - name: pytest
        run:
          poetry run python -m pytest tests/ --showlocals -vv -m "not django"

  unit-tests-on-windows:
    name: Python 3.10 on Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.10"
          cache: "poetry"

      - run:
          poetry env use C:\hostedtoolcache\windows\Python\3.8.10\x86\python.exe
      - run: poetry run python --version
      - run: poetry install
        if: steps.setup-python.outputs.cache-hit != 'true'

      - name: pytest
        run:
          poetry run python -m pytest tests/ --showlocals -vv -m "not django"

  django-unit-tests:
    strategy:
      matrix:
        django: ["4.0", "3.2"]

    name: Django ${{ matrix.django }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        id: setup-python
        with:
          python-version: "3.10"
          cache: "poetry"

      - run: poetry env use python3.10
      - run: poetry install
        if: steps.setup-python.outputs.cache-hit != 'true'

      - name: Install django ${{ matrix.django }}
        run: poetry add --python ^3.10 django@^${{ matrix.django }}

      - name: pytest
        run:
          poetry run python -m pytest --showlocals -vv -m django
